import type { TemplateCategory, TemplateMeta } from "@/types/template";

/**
 * Single source of truth for the gallery, sitemap and docs.
 * Adding a template = add an entry here + a folder under src/templates.
 */
export const templates: TemplateMeta[] = [
  // ── Chartered accountants ──────────────────────────────────────────
  {
    slug: "ca-corporate",
    category: "ca",
    name: "Corporate CA",
    demoBrand: "Aurum & Associates",
    description:
      "An institutional practice site for a chartered accountancy firm — compliance calendar, service depth and partner credibility above the fold.",
    href: "/templates/ca/corporate",
    themeClass: "theme-ca",
    swatch: ["#0F2544", "#B08A3C"],
    sections: [
      "Sticky navigation",
      "Hero with credibility band",
      "Service grid",
      "Industries served",
      "Engagement process",
      "Partners",
      "Testimonials",
      "FAQ",
      "Consultation form",
    ],
    status: "stable",
  },
  {
    slug: "ca-boutique",
    category: "ca",
    name: "Boutique Tax Chamber",
    demoBrand: "Kothari Tax Chambers",
    description:
      "A single-practitioner tax chamber. Quiet, typographic and personal — built for a CA who wants fewer, better clients rather than a firm-scale funnel.",
    href: "/templates/ca/boutique",
    themeClass: "theme-ca-boutique",
    swatch: ["#263A30", "#B06A3C"],
    sections: [
      "Minimal navigation",
      "Letter-style hero",
      "How the chamber works",
      "Services list",
      "Who it is for",
      "Practitioner note",
      "Fee philosophy",
      "FAQ",
      "Enquiry form",
    ],
    status: "stable",
  },
  {
    slug: "ca-startup",
    category: "ca",
    name: "Startup CFO Desk",
    demoBrand: "LedgerLab",
    description:
      "A productised finance-and-compliance subscription for funded startups — pricing tiers, deliverable stack and a diligence-readiness pitch.",
    href: "/templates/ca/startup",
    themeClass: "theme-ca-startup",
    swatch: ["#4F46E5", "#0D9E6E"],
    sections: [
      "Product navigation",
      "Metric hero",
      "The stack you get",
      "Pricing tiers",
      "Diligence readiness",
      "Integrations",
      "Founder testimonials",
      "FAQ",
      "Book a demo",
    ],
    status: "stable",
  },

  // ── Doctors & clinics ──────────────────────────────────────────────
  {
    slug: "doctor-clinic",
    category: "doctor",
    name: "Clinic",
    demoBrand: "Aarogya Clinic",
    description:
      "A single-practitioner clinic site built around one job: getting a patient to book. Appointment card, timings, treatments and directions.",
    href: "/templates/doctor/clinic",
    themeClass: "theme-doctor",
    swatch: ["#0D736C", "#CA6914"],
    sections: [
      "Utility bar + navigation",
      "Hero with booking card",
      "Specialisations",
      "About the doctor",
      "Treatments",
      "Clinic timings",
      "Patient stories",
      "FAQ",
      "Appointment form",
    ],
    status: "stable",
  },
  {
    slug: "doctor-dental",
    category: "doctor",
    name: "Dental Studio",
    demoBrand: "Smile Studio Dental",
    description:
      "A dental practice site that sells outcomes rather than procedures — treatment menu with indicative pricing, sittings, and a nervous-patient promise.",
    href: "/templates/doctor/dental",
    themeClass: "theme-doctor-dental",
    swatch: ["#0E74C8", "#0DA594"],
    sections: [
      "Navigation with call bar",
      "Hero with trust markers",
      "Treatment menu & pricing",
      "The visit, step by step",
      "Technology on site",
      "Nervous patients",
      "Before / after gallery",
      "Reviews",
      "FAQ + booking form",
    ],
    status: "stable",
  },
  {
    slug: "doctor-hospital",
    category: "doctor",
    name: "Multi-speciality Hospital",
    demoBrand: "Sanjeevani Hospital",
    description:
      "An institutional hospital site: emergency banner, department directory, consultant search, health check packages and insurance panels.",
    href: "/templates/doctor/hospital",
    themeClass: "theme-doctor-hospital",
    swatch: ["#112D5B", "#CA2837"],
    sections: [
      "Emergency bar",
      "Hero with quick actions",
      "Centres of excellence",
      "Find a consultant",
      "Facilities & accreditation",
      "Health check packages",
      "Insurance & TPA",
      "Patient information",
      "Appointment form",
    ],
    status: "stable",
  },

  // ── Lawyers & law firms ────────────────────────────────────────────
  {
    slug: "lawyer-firm",
    category: "lawyer",
    name: "Law Firm",
    demoBrand: "Mehta & Partners",
    description:
      "An editorial, serif-led litigation practice site — practice areas, reported matters, counsel profiles and a confidential enquiry form.",
    href: "/templates/lawyer/firm",
    themeClass: "theme-lawyer",
    swatch: ["#1A202C", "#A07946"],
    sections: [
      "Navigation",
      "Editorial hero",
      "Practice areas",
      "Firm record",
      "Counsel profiles",
      "Reported matters",
      "Client testimonials",
      "Offices",
      "Enquiry form",
    ],
    status: "stable",
  },
  {
    slug: "lawyer-advocate",
    category: "lawyer",
    name: "Solo Advocate",
    demoBrand: "Adv. Kavita Menon",
    description:
      "A solo practitioner in family, matrimonial and criminal matters. Warmer, plainer and written for a client in distress rather than a general counsel.",
    href: "/templates/lawyer/advocate",
    themeClass: "theme-lawyer-advocate",
    swatch: ["#6A1E2E", "#A67C46"],
    sections: [
      "Navigation",
      "Reassurance hero",
      "Matters handled",
      "What happens first",
      "About the advocate",
      "Courts of practice",
      "Fees explained",
      "FAQ",
      "Confidential enquiry",
    ],
    status: "stable",
  },
  {
    slug: "lawyer-corporate",
    category: "lawyer",
    name: "Corporate & Technology",
    demoBrand: "Sterling Legal",
    description:
      "A transactional firm for founders and investors — deal sheet, sector coverage, turnaround commitments and fixed-fee startup packages.",
    href: "/templates/lawyer/corporate",
    themeClass: "theme-lawyer-corporate",
    swatch: ["#0F1E3C", "#1473EB"],
    sections: [
      "Navigation",
      "Deal-led hero",
      "Services by stage",
      "Selected transactions",
      "Sector coverage",
      "Fixed-fee packages",
      "Team",
      "FAQ",
      "Enquiry form",
    ],
    status: "stable",
  },

  // ── Architects & interiors ─────────────────────────────────────────
  {
    slug: "architect-studio",
    category: "architect",
    name: "Architecture Studio",
    demoBrand: "Terrain Studio",
    description:
      "A monochrome, project-led studio site. Sharp corners, big type, an index of works and a practice statement that reads like a monograph.",
    href: "/templates/architect/studio",
    themeClass: "theme-architect-studio",
    swatch: ["#181818", "#AC542C"],
    sections: [
      "Minimal navigation",
      "Full-bleed hero",
      "Selected works index",
      "Practice statement",
      "Services & scope",
      "Process",
      "Recognition & press",
      "Studio & people",
      "Project enquiry",
    ],
    status: "stable",
  },
  {
    slug: "architect-interior",
    category: "architect",
    name: "Interior Design",
    demoBrand: "Casa Interiors",
    description:
      "A residential interiors practice — packages by home size, a room-by-room offering, material palettes and a transparent timeline.",
    href: "/templates/architect/interior",
    themeClass: "theme-architect-interior",
    swatch: ["#7A3E2C", "#9E8052"],
    sections: [
      "Navigation",
      "Warm hero with consult CTA",
      "Design packages",
      "Room by room",
      "Material palettes",
      "How a project runs",
      "Client homes",
      "FAQ",
      "Consultation form",
    ],
    status: "stable",
  },

  {
    slug: "architect-workplace",
    category: "architect",
    name: "Workplace Design",
    demoBrand: "Kernel Workspace",
    description:
      "Commercial office fit-out for companies — cost per seat, density planning, and phasing that keeps the office running while the work happens around it.",
    href: "/templates/architect/workplace",
    themeClass: "theme-architect-workplace",
    swatch: ["#173F4F", "#4F7522"],
    sections: [
      "Navigation",
      "Technical hero",
      "Cost per seat",
      "What we deliver",
      "Density & space standards",
      "Live-office phasing",
      "Completed fit-outs",
      "Sustainability",
      "Brief enquiry",
    ],
    status: "stable",
  },

  // ── Real estate & construction ─────────────────────────────────────
  {
    slug: "realestate-developer",
    category: "real-estate",
    name: "Property Developer",
    demoBrand: "Meridian Developers",
    description:
      "A residential developer site built around inventory — project cards with configuration and price bands, amenities, construction status and a site-visit form.",
    href: "/templates/real-estate/developer",
    themeClass: "theme-realestate-developer",
    swatch: ["#103E30", "#AC8842"],
    sections: [
      "Navigation",
      "Project hero",
      "Current projects",
      "Configurations & pricing",
      "Amenities",
      "Construction status",
      "Why buy here",
      "RERA & legal",
      "Site visit form",
    ],
    status: "stable",
  },
  {
    slug: "realestate-construction",
    category: "real-estate",
    name: "Construction Company",
    demoBrand: "Ironwood Constructions",
    description:
      "A contracting firm site aimed at procurement teams — capability statement, plant and equipment, safety record, completed projects and a tender enquiry.",
    href: "/templates/real-estate/construction",
    themeClass: "theme-realestate-construction",
    swatch: ["#1E293B", "#D98A08"],
    sections: [
      "Navigation",
      "Capability hero",
      "What we build",
      "Completed projects",
      "Plant & equipment",
      "Safety & quality record",
      "Certifications",
      "Clients",
      "Tender enquiry",
    ],
    status: "stable",
  },

  {
    slug: "realestate-brokerage",
    category: "real-estate",
    name: "Property Brokerage",
    demoBrand: "Anchor Property Advisors",
    description:
      "A resale and rental brokerage — live listings, locality guides, published commission, and separate tracks for buyers, sellers, tenants and landlords.",
    href: "/templates/real-estate/brokerage",
    themeClass: "theme-realestate-brokerage",
    swatch: ["#243B6B", "#D9452F"],
    sections: [
      "Navigation with search",
      "Listing hero",
      "Featured listings",
      "Buy / rent / sell tracks",
      "Locality guides",
      "Commission, published",
      "Paperwork handled",
      "Client outcomes",
      "Enquiry form",
    ],
    status: "stable",
  },

  // ── Education & coaching ───────────────────────────────────────────
  {
    slug: "education-coaching",
    category: "education",
    name: "Competitive Coaching",
    demoBrand: "Apex Academy",
    description:
      "A JEE and NEET coaching institute site that leads with results — selection numbers, batch structure, faculty, test series and an admission enquiry.",
    href: "/templates/education/coaching",
    themeClass: "theme-education-coaching",
    swatch: ["#1D3A9E", "#E4620C"],
    sections: [
      "Navigation with admissions CTA",
      "Results hero",
      "Selections board",
      "Courses & batches",
      "Faculty",
      "Test series & doubt support",
      "Fee & scholarships",
      "Parent testimonials",
      "Admission enquiry",
    ],
    status: "stable",
  },
  {
    slug: "education-tuition",
    category: "education",
    name: "Tuition Centre",
    demoBrand: "BrightMinds Tuition",
    description:
      "A neighbourhood tuition centre for classes 6 to 12. Friendly, batch-timing led, and written for a parent deciding on a Tuesday evening.",
    href: "/templates/education/tuition",
    themeClass: "theme-education-tuition",
    swatch: ["#6D3EC2", "#B47A0C"],
    sections: [
      "Navigation",
      "Parent-facing hero",
      "Classes & subjects",
      "Batch timetable",
      "How we teach",
      "Teachers",
      "Fees & demo class",
      "Parent reviews",
      "Enrolment form",
    ],
    status: "stable",
  },

  {
    slug: "education-arts",
    category: "education",
    name: "Performing Arts Academy",
    demoBrand: "Swaralaya Academy",
    description:
      "A music and dance academy — disciplines and instruments, graded examinations, teacher lineages, the annual recital, and fees per discipline.",
    href: "/templates/education/arts",
    themeClass: "theme-education-arts",
    swatch: ["#7A2E4E", "#0E7C7B"],
    sections: [
      "Navigation",
      "Recital hero",
      "Disciplines & instruments",
      "Graded examinations",
      "Gurus & faculty",
      "Class formats & fees",
      "The annual recital",
      "Student outcomes",
      "Trial class form",
    ],
    status: "stable",
  },

  // ── Fashion & design ───────────────────────────────────────────────
  {
    slug: "fashion-couture",
    category: "fashion",
    name: "Couture Atelier",
    demoBrand: "Atelier Rhea",
    description:
      "A made-to-measure couture house. Editorial, near-monochrome, built around collections, the commission process and an appointment-only atelier.",
    href: "/templates/fashion/couture",
    themeClass: "theme-fashion-couture",
    swatch: ["#161414", "#A86A6A"],
    sections: [
      "Editorial navigation",
      "Collection hero",
      "Collections index",
      "The commission process",
      "Atelier & craft",
      "Fittings & timeline",
      "Press",
      "Appointment enquiry",
      "Stockists",
    ],
    status: "stable",
  },
  {
    slug: "fashion-boutique",
    category: "fashion",
    name: "Boutique Label",
    demoBrand: "Indigo Thread",
    description:
      "A small-batch clothing label — lookbook grid, fabric and provenance story, size and care guidance, wholesale enquiries and a stockist list.",
    href: "/templates/fashion/boutique",
    themeClass: "theme-fashion-boutique",
    swatch: ["#2E306E", "#BA6C36"],
    sections: [
      "Navigation",
      "Lookbook hero",
      "The current drop",
      "Fabric & provenance",
      "Made-to-order",
      "Size & care",
      "Stockists",
      "Wholesale enquiry",
      "Newsletter",
    ],
    status: "stable",
  },

  {
    slug: "fashion-stylist",
    category: "fashion",
    name: "Personal Stylist",
    demoBrand: "Form & Figure",
    description:
      "Image consulting as a service, not a shop — wardrobe audits, personal shopping, corporate workshops, session pricing and a virtual option.",
    href: "/templates/fashion/stylist",
    themeClass: "theme-fashion-stylist",
    swatch: ["#2B3A36", "#9C4A70"],
    sections: [
      "Navigation",
      "Service hero",
      "Services & session pricing",
      "How a styling engagement runs",
      "Wardrobe audit, explained",
      "Corporate workshops",
      "Client transformations",
      "FAQ",
      "Booking form",
    ],
    status: "stable",
  },

  // ── Fitness & coaching ─────────────────────────────────────────────
  {
    slug: "fitness-trainer",
    category: "fitness",
    name: "Personal Trainer",
    demoBrand: "Pawar Strength",
    description:
      "A solo coach working the gym floor. The one dark template in the kit — near-black and volt lime, with WhatsApp as the primary way in.",
    href: "/templates/fitness/trainer",
    themeClass: "theme-fitness-trainer",
    swatch: ["#0C0C0C", "#A3E635"],
    sections: [
      "Hero with WhatsApp CTA",
      "Training programs",
      "About me",
      "Certifications",
      "Nutrition & diet",
      "Research & knowledge",
      "Client testimonials",
      "Location & service areas",
      "WhatsApp & contact",
    ],
    status: "stable",
  },
  {
    slug: "fitness-online",
    category: "fitness",
    name: "Online Coaching",
    demoBrand: "Foundry Coaching",
    description:
      "Remote coaching as a subscription — how the week runs, plan tiers with pricing, transformations, and check-ins across time zones.",
    href: "/templates/fitness/online",
    themeClass: "theme-fitness-online",
    swatch: ["#A21CAF", "#0F766E"],
    sections: [
      "Hero with plan pricing",
      "How online coaching runs",
      "Training programs",
      "Nutrition & diet",
      "About & certifications",
      "Research & knowledge",
      "Client transformations",
      "Time zones & service areas",
      "WhatsApp & apply",
    ],
    status: "stable",
  },
  {
    slug: "fitness-studio",
    category: "fitness",
    name: "Strength Studio",
    demoBrand: "Anvil Strength",
    description:
      "A small-group strength facility — class timetable, coach roster with certifications, memberships, floor inventory and trial booking.",
    href: "/templates/fitness/studio",
    themeClass: "theme-fitness-studio",
    swatch: ["#1E3A5F", "#4D7C0F"],
    sections: [
      "Hero with trial booking",
      "Training programs",
      "Weekly timetable",
      "About the studio",
      "Coaches & certifications",
      "Nutrition & diet",
      "Research & knowledge",
      "Member testimonials",
      "Location, WhatsApp & contact",
    ],
    status: "stable",
  },
];

export const categoryLabels: Record<TemplateCategory, string> = {
  ca: "Chartered Accountants",
  doctor: "Doctors & Clinics",
  lawyer: "Lawyers & Law Firms",
  architect: "Architects & Interiors",
  "real-estate": "Real Estate & Construction",
  education: "Education & Coaching",
  fashion: "Fashion & Design",
  fitness: "Fitness & Coaching",
};

/** Display order for the gallery. */
export const categoryOrder: TemplateCategory[] = [
  "ca",
  "doctor",
  "lawyer",
  "architect",
  "real-estate",
  "education",
  "fashion",
  "fitness",
];

export function templatesByCategory(category: TemplateCategory) {
  return templates.filter((template) => template.category === category);
}
